version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

clone_folder: c:\projects\cfgtrace

configuration:
  - Debug

platform: x86

install:
  # All external dependencies are installed in C:\projects\deps
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  # Install Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version
  # Install Catch2
  - set CATCH2_URL="https://github.com/catchorg/Catch2.git"
  - git clone %CATCH2_URL% catch
  - cd catch
  - cmake -DBUILD_TESTING=OFF -Bbuild -H.
  - cmake --build build/ --target install
  # Install ctest
  - ctest --version

build:
  parallel: true
  verbosity: detailed

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86 10.0.16299.0
  - cd C:\projects\cfgtrace

build_script:
  - cmake -DBUILD_DEMO=ON -DDBUILD_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -G Ninja -Bbuild/ -H.
  - ninja -v -C build -j2 cfgtrace
  - ninja -v -C build -j2 first_demo
  - ninja -v -C build -j2 second_demo

test_script:
  - ninja -v -C build -j2 cfgtracetest
  - cd build
  - ctest -VV -j2 -C Debug --build-and-test